package com.jvm_bloggers.entities.metadata;

public interface MetadataKeys {

    String MAILING_TEMPLATE = "MAILING_TEMPLATE";

    String ADMIN_EMAIL = "ADMIN_EMAIL";

    String DEFAULT_MAILING_TEMPLATE = "DEFAULT_MAILING_TEMPLATE";

    String MAILING_GREETING = "MAILING_GREETING";
    String HEADING_TEMPLATE = "HEADING_TEMPLATE";
    String VARIA_TEMPLATE = "VARIA_TEMPLATE";
    String MAILING_SIGNATURE = "MAILING_SIGNATURE";

    String DATE_OF_LAST_FETCHING_BLOGGERS = "DATE_OF_LAST_FETCHING_BLOGGERS";
    String DATE_OF_LAST_FETCHING_BLOG_POSTS = "DATE_OF_LAST_FETCHING_BLOG_POSTS";

}
