name: CI
on:
  pull_request:
  push:
    branches:
      - master
  release:
    types:
      - released

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up JVM
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'
      - name: Check
        run: ./gradlew check

  deploy:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up JVM
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'
      - name: Set up environment variables for Docker
        run: |
          echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> $GITHUB_ENV
          echo "DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}" >> $GITHUB_ENV
          echo "DOCKER_EMAIL=${{ secrets.DOCKER_EMAIL }}" >> $GITHUB_ENV
      - name: Build
        run: ./gradlew clean build
      - name: Build Docker image and push to Docker Hub
        run: ./gradlew dockerPush
